\c postgres

DROP database cnfadm;

CREATE database cnfadm;

\c cnfadm

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

CREATE TABLE canada_food_group (
	canada_food_group_id float NOT NULL,
	canada_food_group_code float,
	canada_food_group_desc_e varchar(100),
	canada_food_group_desc_f varchar(100),
	publication_code varchar(10)
);
COMMENT ON TABLE canada_food_group IS E'This is a list table with all the Canada Food Guide Groups. Canada Food Guide Groups are base on similar characteristics of the foods. Shared with NSS';
COMMENT ON COLUMN canada_food_group.canada_food_group_code IS E'A number given by Nutrition Research Division that uniquely identifies a Canada Food Guide Group.';
COMMENT ON COLUMN canada_food_group.canada_food_group_desc_f IS E'French description of a Canada Food Guide Group.';
COMMENT ON COLUMN canada_food_group.canada_food_group_id IS E'Unique number generated by Oracle to identifies a Canada Food Guide Group';
COMMENT ON COLUMN canada_food_group.canada_food_group_desc_e IS E'English description of a Canada Food Guide Group.';
ALTER TABLE canada_food_group ADD PRIMARY KEY (canada_food_group_id);

CREATE TABLE canada_food_subgroup (
	canada_food_subgroup_id float NOT NULL,
	canada_food_subgroup_code float,
	canada_food_subgroup_desc_e varchar(100),
	canada_food_subgroup_desc_f varchar(100),
	canada_food_group_id float,
	publication_code varchar(10)
);
COMMENT ON TABLE canada_food_subgroup IS E'This is a list table with all the Canada Food Guide SubGroups . Canada Food Guide Subroups are base on similar characteristics of the foods groups. Shared with NSS';
COMMENT ON COLUMN canada_food_subgroup.canada_food_group_id IS E'Unique number to identifies a Canada Food Guide Group. (CANADA_FOOD_GROUP)';
COMMENT ON COLUMN canada_food_subgroup.canada_food_subgroup_desc_f IS E'French description of a Canada Food Guide SubGroup.';
COMMENT ON COLUMN canada_food_subgroup.canada_food_subgroup_code IS E'A number given by Nutrition Research Division that uniquely identifies a Canada Food Guide SubGroup.';
COMMENT ON COLUMN canada_food_subgroup.canada_food_subgroup_desc_e IS E'English description of a Canada Food Guide SubGroup.';
COMMENT ON COLUMN canada_food_subgroup.canada_food_subgroup_id IS E'Unique number generated by Oracle to identifies a Canada Food Guide SubGroup';
ALTER TABLE canada_food_subgroup ADD PRIMARY KEY (canada_food_subgroup_id);

CREATE TABLE measure_type (
	m_type_id float NOT NULL,
	m_type_desc varchar(255),
	m_type_abbrv varchar(6) NOT NULL,
	m_type_user_selectable float NOT NULL,
	m_type_desc_f varchar(255)
) ;
COMMENT ON TABLE measure_type IS E'Contains a list of measures types (in English and French).. The measure type drives processing in portion quantity calculations. New table added in version 3. This table is a support or "list" table. Shared with NSS';
COMMENT ON COLUMN measure_type.m_type_desc IS E'Provides an English description of the measure type.';
COMMENT ON COLUMN measure_type.m_type_desc_f IS E'Provides a French description of the measure type.';
COMMENT ON COLUMN measure_type.m_type_abbrv IS E'Provides an abbreviation of the measure type.';
COMMENT ON COLUMN measure_type.m_type_user_selectable IS E'1= a user can select this type when creating a new measure; 0= this type is only used by the appplication to apply business rules';
COMMENT ON COLUMN measure_type.m_type_id IS E'Generated number by Oracle that uniquely identifies a measure type.';
ALTER TABLE measure_type ADD UNIQUE (m_type_desc);
ALTER TABLE measure_type ADD PRIMARY KEY (m_type_id);
ALTER TABLE measure_type ADD UNIQUE (m_type_abbrv);
ALTER TABLE measure_type ADD UNIQUE (m_type_desc_f);

CREATE TABLE nutr_name (
	nutr_c smallint NOT NULL,
	nutr_symbol varchar(10) NOT NULL,
	nutr_name varchar(200),
	unit varchar(8) NOT NULL,
	sequence_c float,
	nutr_name_f varchar(200),
	nutr_code float NOT NULL,
	nutr_web float DEFAULT 1,
	tagname varchar(20),
	nutr_active_flag float,
	nutr_decimal_place float,
	nutr_web_order float,
	nutr_web_name_e varchar(150),
	nutr_web_name_f varchar(150),
	nutrient_group_id float,
	publication_code varchar(10)
) ;
COMMENT ON TABLE nutr_name IS E'List the nutrients. Nutrients are chemicals found in foods that are critical to human growth and function. This table is a support or "list" table. Shared with NSS';
COMMENT ON COLUMN nutr_name.nutr_c IS E'Generated number by Oracle that uniquely identifies a nutrient.';
COMMENT ON COLUMN nutr_name.nutr_name IS E'English name for a nutrient.';
COMMENT ON COLUMN nutr_name.sequence_c IS E'The order in which the nutrient will be display in Canadian Nutrient File application.';
COMMENT ON COLUMN nutr_name.nutr_code IS E'Unique number given to a nutrient by Nutrition Research.';
COMMENT ON COLUMN nutr_name.nutr_decimal_place IS E'Number of decimal that will show in the nutrient value in the Serving Size.';
COMMENT ON COLUMN nutr_name.nutr_web_name_e IS E'English name for a nutrient on the WEB. Version 2.4';
COMMENT ON COLUMN nutr_name.nutr_active_flag IS E'Marks if a nutrient is active show on Report and serving size 0 = No 1 = Yes.';
COMMENT ON COLUMN nutr_name.nutr_symbol IS E'Provides an abbreviation for the nutrient name.';
COMMENT ON COLUMN nutr_name.nutr_name_f IS E'French name for a nutrient.';
COMMENT ON COLUMN nutr_name.nutr_web IS E'Marks if a nutrient will show on the WEB Serving Size.';
COMMENT ON COLUMN nutr_name.tagname IS E'International abbreviation for a nutrient.';
COMMENT ON COLUMN nutr_name.nutrient_group_id IS E'Represent a nutrient group for the WEB (NUTRIENT GROUP)';
COMMENT ON COLUMN nutr_name.nutr_web_order IS E'The order in which the nutrient will be display on the WEB Version 2.4';
COMMENT ON COLUMN nutr_name.nutr_web_name_f IS E'French name for a nutrient on the WEB.. Version 2.4';
COMMENT ON COLUMN nutr_name.unit IS E'Consist of a maximum of eight (8) describing the unit of measure.';
ALTER TABLE nutr_name ADD PRIMARY KEY (nutr_c);
ALTER TABLE nutr_name ADD UNIQUE (nutr_code);

CREATE TABLE conv_factor (
	conv_factor_c bigint NOT NULL,
	food_c float,
	measure_id bigint NOT NULL,
	conv_factor float,
	valid_null_cf smallint,
	cf_ref_id integer,
	comment_t varchar(255),
	cf_comment_f varchar(255),
	date_entry timestamp NOT NULL,
	date_end timestamp,
	publication_code varchar(6),
	seq_web float,
	flag_cfg varchar(1) DEFAULT 'N',
	flag_reference_amount varchar(1) DEFAULT 'N',
	no_serving float,
	show_serving_size varchar(1) DEFAULT 'N',
	cf_owner bigint NOT NULL,
	shared_cf smallint NOT NULL DEFAULT 0,
	flag_report varchar(1) DEFAULT 'N',
	fn_sys_user_create_c bigint,
	fn_sys_user_edit_c bigint,
	publication_flag varchar(1) DEFAULT 'N'
) ;
COMMENT ON TABLE conv_factor IS E'Merged Conversion Factor Table (CNF and NSS). Defines a portion size and converts it to a gram amount. Shared with NSS';
COMMENT ON COLUMN conv_factor.no_serving IS E'Number of CFGHE servings that this conversion factor represents (generally= 1, can be fractional)';
COMMENT ON COLUMN conv_factor.flag_reference_amount IS E'(Y or N field) Marks if a conversion factor is the reference amount';
COMMENT ON COLUMN conv_factor.show_serving_size IS E'(Y or N field) Marks if the conversion factor will show in the Serving Size module and on the WEB';
COMMENT ON COLUMN conv_factor.publication_flag IS E'Flags conversion factors for recipe download files.';
COMMENT ON COLUMN conv_factor.publication_code IS E'Code for Publication (only ADD or CHANGE).';
COMMENT ON COLUMN conv_factor.fn_sys_user_edit_c IS E'Last user to edit this conversion factor';
COMMENT ON COLUMN conv_factor.cf_owner IS E'Only the owner system (CNF or NSS) can update or delete a conversion factor.';
COMMENT ON COLUMN conv_factor.flag_cfg IS E'Either ''Y'' or "N".  If ''Y'', this is the CF that corresponds to a CFGHE serving for this food.';
COMMENT ON COLUMN conv_factor.seq_web IS E'Will be used to order measure on the WEB';
COMMENT ON COLUMN conv_factor.fn_sys_user_create_c IS E'User who created the conversion factor';
COMMENT ON COLUMN conv_factor.food_c IS E'Where present, the CF is food-specific; otherwise, it is not.';
COMMENT ON COLUMN conv_factor.valid_null_cf IS E'1 = CONV_FACTOR value was confirmed to be valid even though is is a NULL value';
COMMENT ON COLUMN conv_factor.shared_cf IS E'1= CF is shared: the non-owner can select it, but not update or delete it.';
COMMENT ON COLUMN conv_factor.conv_factor IS E'Factor that, when multiplied by the quantity used of this measure, will give the corresponding gram weight. For measure_type U only, the app will multiply this value by 100';
ALTER TABLE conv_factor ADD UNIQUE (food_c,measure_id,date_end);
ALTER TABLE conv_factor ADD PRIMARY KEY (conv_factor_c);
CREATE INDEX measure_id_ix ON conv_factor (measure_id);
CREATE UNIQUE INDEX food_c_measure_id_date_end_uk1 ON conv_factor (food_c, measure_id, date_end);

CREATE TABLE food_name (
	food_c float NOT NULL,
	eng_name varchar(255) NOT NULL,
	fr_name varchar(255),
	food_desc varchar(255),
	food_desc_f varchar(255),
	nut_can_c float,
	cnf_flag smallint NOT NULL,
	date_entry timestamp,
	date_change timestamp,
	date_end timestamp,
	date_public timestamp,
	comment_t varchar(255),
	group_c bigint,
	source_c bigint,
	item_c bigint,
	country_c varchar(10),
	cnf_release varchar(60),
	food_reference varchar(200),
	scientific_name varchar(100),
	publication_flag varchar(1) DEFAULT 'N',
	publication_code varchar(6),
	sequence_c bigint,
	legacy_group_c float,
	fn_comment_f varchar(255),
	fn_db_source_c bigint NOT NULL,
	fn_recipe_flg smallint NOT NULL,
	fn_system_view_c bigint NOT NULL,
	fn_fat_change decimal(38,2),
	fn_moisture_change decimal(38,2),
	fn_sys_user_create_c bigint,
	fn_sys_user_edit_c bigint,
	fn_template_c float,
	fn_temp smallint DEFAULT 0,
	fn_archived timestamp,
	fn_legacy_c varchar(50),
	us_recipe_c float,
	usda_modified smallint,
	usda_temp varchar(10),
	canada_food_subgroup_id float,
	cfghe_flag smallint,
	orig_canada_food_subgroup_id float,
	food_owner bigint NOT NULL,
	shared_food smallint NOT NULL,
	common_nm_e varchar(255),
	common_nm_f varchar(255),
	candi_rec_num varchar(12),
	inheritance_flag smallint NOT NULL DEFAULT 0,
	food_code float NOT NULL
);
COMMENT ON TABLE food_name IS E'This is one of the main tables It contains a description of each basic food (CNF) or recipe/ ingredient (NSS) in English and French as well as dates, comments, food source and more. Shared with NSS';
COMMENT ON COLUMN food_name.fn_db_source_c IS E'Which database this food comes from';
COMMENT ON COLUMN food_name.inheritance_flag IS E'Was this food inherited following a deletion ? 0= No; 1= Yes and its ownership transfer needs to be confirmed.';
COMMENT ON COLUMN food_name.date_entry IS E'Food creation date';
COMMENT ON COLUMN food_name.food_code IS E'User-defined code  that is controlled by a CNFADM sequence (name starts with FOOD_CODE).';
COMMENT ON COLUMN food_name.eng_name IS E'Provides the abbreviate English name for a food';
COMMENT ON COLUMN food_name.orig_canada_food_subgroup_id IS E'Link to a Canada''s Food Guide to Healthy Eating food subgroup.  Initial subgroup as determined by SAS and CNF';
COMMENT ON COLUMN food_name.fn_system_view_c IS E'Which system can view this food';
COMMENT ON COLUMN food_name.food_desc IS E'Nullable because it is not mandatory for recipes';
COMMENT ON COLUMN food_name.fn_sys_user_create_c IS E'User who created the food';
COMMENT ON COLUMN food_name.fn_temp IS E'Temporary food. Place holder for a food to be created; has no nutrient, food group, etc: just a name. Users can select it. Will later be replaced with a normal food.';
COMMENT ON COLUMN food_name.fn_recipe_flg IS E'1 = True: Is this food a recipe (i.e. does it have ingredients)?';
COMMENT ON COLUMN food_name.date_end IS E'Possibly kept here to parallell ARC_FOOD_NAME.';
COMMENT ON COLUMN food_name.common_nm_e IS E'English name used in the publication Nutrient Values of Some Common Foods.';
COMMENT ON COLUMN food_name.date_change IS E'Documents when the food was last modified and that a copy of that food was archived. Only the last change date is maintained.';
COMMENT ON COLUMN food_name.canada_food_subgroup_id IS E'Link to a Canada''s Food Guide to Healthy Eating food subgroup. CFGHE groups and subgroups are managed by the CNF app.';
COMMENT ON COLUMN food_name.usda_temp IS E'Was called the Candi Code in the Candi system. Still used by USDA for this recipe.';
COMMENT ON COLUMN food_name.fn_legacy_c IS E'Candi code with C or CX prefix. Record number moved to CANDI_REC_NUM';
COMMENT ON COLUMN food_name.candi_rec_num IS E'Record code in the Candi system: equal to the record offset in the candidat.x03 file. Used as an PK in Candi. For backward reference.';
COMMENT ON COLUMN food_name.common_nm_f IS E'French name used in the publication Nutrient Values of Some Common Foods.';
COMMENT ON COLUMN food_name.us_recipe_c IS E'USDA code of recipes (RECING survey_code)';
COMMENT ON COLUMN food_name.sequence_c IS E'Inherited from CNF';
COMMENT ON COLUMN food_name.cnf_flag IS E'Inherited from CNF';
COMMENT ON COLUMN food_name.scientific_name IS E'Scientific name of the food.';
COMMENT ON COLUMN food_name.source_c IS E'Indicates data source of food (GROUP + SOURCE (0) + ITEM =  USDA Food Code)';
COMMENT ON COLUMN food_name.food_reference IS E'Refers to the source of information (i.e. name of publication).';
COMMENT ON COLUMN food_name.fr_name IS E'Provides the abbreviate French name for a food';
COMMENT ON COLUMN food_name.usda_modified IS E'A recipe that comes from USDA, but that was modified in this db';
COMMENT ON COLUMN food_name.country_c IS E'Combination of letters that refer to the country and numbers that identify the food_c (e.g. US1324)';
COMMENT ON COLUMN food_name.fn_moisture_change IS E'Recipes only: processing will reduce resulting moisture amount in food by this percentage if value is <0';
COMMENT ON COLUMN food_name.fn_fat_change IS E'Recipes only: processing will reduce resulting fat amount in food by this percentage if value is <0';
COMMENT ON COLUMN food_name.food_c IS E'Generated number by Oracle that uniquely identifies a food.';
COMMENT ON COLUMN food_name.food_owner IS E'Owner of the food 2= NSS, 3 = CNF';
COMMENT ON COLUMN food_name.date_public IS E'Refers to the date when the food information became public.';
COMMENT ON COLUMN food_name.group_c IS E'CNF food group code. Used essentially to link to the retention groups available for this food (based on CNF group)  (GROUP + SOURCE (0) + ITEM =  USDA Food Code)';
COMMENT ON COLUMN food_name.fn_sys_user_edit_c IS E'Last user to edit this food';
COMMENT ON COLUMN food_name.fn_template_c IS E'Unsure of meaning. Thought it was the recipe (model) a standard recipe is based on, but tested negatively.';
COMMENT ON COLUMN food_name.item_c IS E'Last 3 digits of the USDA NDB code. (GROUP + SOURCE (0) + ITEM =  USDA Food Code)';
COMMENT ON COLUMN food_name.legacy_group_c IS E'Candi food group code. More elaborate than the CNF grouping structure.';
COMMENT ON COLUMN food_name.nut_can_c IS E'Inherited from CNF';
COMMENT ON COLUMN food_name.shared_food IS E'1 = Food is shared between CNF and NSS';
COMMENT ON COLUMN food_name.publication_flag IS E'Flag foods that will be part of the Nutrient Value or some common foods publication not the CNF publication.';
COMMENT ON COLUMN food_name.publication_code IS E'Code for Publication (ADD, CHANGE).';
COMMENT ON COLUMN food_name.cfghe_flag IS E'Indicates whether recipe CFGHE group is at the recipe level (value=1) or ingredient level (value=0 or 2)';
ALTER TABLE food_name ADD PRIMARY KEY (food_c);
ALTER TABLE food_name ADD UNIQUE (eng_name);
CREATE UNIQUE INDEX uq_food_code ON food_name (food_code);
CREATE INDEX grp_src_item2_ix ON food_name (group_c, source_c, item_c);
CREATE INDEX fr_name_ix ON food_name (fr_name);
CREATE INDEX group_c2_ix ON food_name (group_c);
CREATE INDEX source_c2_ix ON food_name (source_c);

